git:
  submodules: false
os:
  - linux
  - osx
sudo: required
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
before_install:
  - mkdir node_modules
  - mkdir node_modules/iobroker
  - mv !(node_modules) node_modules/iobroker/
  - cd node_modules/iobroker/
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CC=clang++; export CXX=clang++; export CXXFLAGS=-std=c++11; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi'
install:
  - export NPMVERSION = $(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $(echo "$NPMVERSION < 5") ]]; then sudo env "PATH=$PATH" $(which npm) install --unsafe-perm; fi'
  - 'if [[ $(echo "$NPMVERSION > 4") ]]; then ! sudo env "PATH=$PATH" $(which npm) install --unsafe-perm; fi'
  - 'if [[ $(echo "$NPMVERSION > 4") ]]; then npm install -g npm@4; fi'
  - 'if [[ $(echo "$NPMVERSION > 4") ]]; then sudo env "PATH=$PATH" $(which npm) install --unsafe-perm; fi'
before_script:
  - cd ../..
  - sudo chmod -R 777 *
  - ps auxww|grep io
  - ./iobroker start
  - cd node_modules/iobroker/
  - npm install request
  - npm install mocha
  - npm install chai
  - sleep 60
  - ps auxww|grep io
  - date
  - cat ../../log/iobroker*.log
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
