version: 'test-{build}'

# Test against this version of Node.js
environment:
  matrix:
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"

platform:
  - x86
  - x64

clone_folder: c:\projects\%APPVEYOR_PROJECT_NAME%\node_modules\iobroker
# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: $NpmVersion = (npm -v).Substring(0,1)
  - ps: $NodeVersion = (node -v).Substring(1,1)
  - ps: Write-Host $NpmVersion
  - ps: Write-Host $NodeVersion
  - ps: if($NodeVersion -eq 0) { $NodeFail = (npm install 2>&1) }
  - ps: if($NodeVersion -eq 0) { Write-Host $NodeFail }
  - ps: if($NodeVersion -eq 0) { if(-Not ($NodeFail -match "ioBroker needs at least nodejs 4.x.")) { exit 1 } }
  - ps: if($NodeVersion -ne 0 -and $NpmVersion -eq 5) { $NpmFail = (npm install 2>&1) }
  - ps: if($NodeVersion -ne 0 -and $NpmVersion -eq 5) { Write-Host $NpmFail }
  - ps: if($NodeVersion -ne 0 -and $NpmVersion -eq 5) { if(-Not ($NpmFail -match "NPM 5 is currently NOT supported!")) { exit 1 } }
  - ps: if($NodeVersion -ne 0 -and $NpmVersion -eq 5) { npm install -g npm@4 }
  # install modules
  - ps: if($NodeVersion -ne 0) { npm install }
# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - echo %cd%
  - node --version
  - npm --version
  - ps: if($NodeVersion -ne 0) { npm install request }
  - ps: if($NodeVersion -ne 0) { npm install mocha }
  - ps: if($NodeVersion -ne 0) { npm install chai }
  - ps: if($NodeVersion -ne 0) { cd ..\.. }
  - ps: if($NodeVersion -ne 0) { Start-Sleep -s 15 }
  - ps: if($NodeVersion -ne 0) { tasklist }
  - serviceIoBroker stop & exit 0
  - ps: if($NodeVersion -ne 0) { Start-Sleep -s 15 }
  - ps: if($NodeVersion -ne 0) { serviceIoBroker start }
  - ps: if($NodeVersion -ne 0) { Start-Sleep -s 60 }
  - ps: if($NodeVersion -ne 0) { tasklist }
  - ps: if($NodeVersion -ne 0) { dir .\ }
  - ps: if($NodeVersion -ne 0) { dir .\log\ }
  - ps: if($NodeVersion -ne 0) { type .\log\iobroker*.log }
  - ps: if($NodeVersion -ne 0) { cd node_modules\iobroker }
  # run tests
  - ps: if($NodeVersion -ne 0) { npm test }

# Don't actually build.
build: off
